#!/usr/bin/env python
#
# Copyright 2007 Doug Hellmann.
#
#
#                         All Rights Reserved
#
# Permission to use, copy, modify, and distribute this software and
# its documentation for any purpose and without fee is hereby
# granted, provided that the above copyright notice appear in all
# copies and that both that copyright notice and this permission
# notice appear in supporting documentation, and that the name of Doug
# Hellmann not be used in advertising or publicity pertaining to
# distribution of the software without specific, written prior
# permission.
#
# DOUG HELLMANN DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN
# NO EVENT SHALL DOUG HELLMANN BE LIABLE FOR ANY SPECIAL, INDIRECT OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

"""Filter proctorbatch --parsable output to show tests which did not pass.

"""

__module_id__ = "$Id: copyright.el 633 2007-05-27 14:15:19Z dhellmann $"

#
# Import system modules
#
import fileinput
import sys

#
# Import Local modules
#
import proctorlib
from proctorlib.parser import ResultFactory, TestResult

#
# Module
#

class proctorfilter(proctorlib.CommandLineApp):
    """
    proctorfilter reads output created by proctorbatch with the
    --parsable option and prints a list of the tests which did not
    pass.
    """
    
    shortArgumentsDescription = "[<log file name> ...]"

    def main(self, *args):
        parser = ResultFactory()

        for line in fileinput.input(args):
            parser.feedLine(line)

        for result in parser.getResults():
            if not result.passed():
                print result.result
                
        return 0

if __name__ == '__main__':
    try:
        success = proctorfilter().run()
    except proctorfilter.HelpRequested:
        pass
    else:
        sys.exit( not success )
